### ISSUE TITLE
Failed migration Craft 2->Craft3

### ISSUE THREAD

**Issue by sgtpenguin** [dukt/videos#44]
### Description
Upgrade from Craft 2-3 Migration fails.  Videos fields are now empty.

### Steps to reproduce

1. Update to from Craft 2 to Craft 3
2. Install Videos and try to "Finish Up"

Any help would be greatly appreciated!  Thanks.

Here's the full error:
```
Unknown Property: Getting unknown property: craft\models\Info::config

Migration: dukt\videos\migrations\m190601_092217_tokens

Output:

> create table {{%videos_tokens}} ... done (time: 0.015s)
> create unique index craft_videos_tokens_gateway_unq_idx on {{%videos_tokens}} (gateway) ... done (time: 0.011s)
Exception: Getting unknown property: craft\models\Info::config (/Users/dylan/Sites/vera-c3/vendor/yiisoft/yii2/base/Component.php:154)
#0 /Users/dylan/Sites/vera-c3/vendor/dukt/videos/src/migrations/m190601_092217_tokens.php(47): yii\base\Component->__get('config')
#1 /Users/dylan/Sites/vera-c3/vendor/dukt/videos/src/migrations/m190601_092217_tokens.php(21): dukt\videos\migrations\m190601_092217_tokens->insertDefaultData()
#2 /Users/dylan/Sites/vera-c3/vendor/craftcms/cms/src/db/Migration.php(52): dukt\videos\migrations\m190601_092217_tokens->safeUp()
#3 /Users/dylan/Sites/vera-c3/vendor/craftcms/cms/src/db/MigrationManager.php(232): craft\db\Migration->up(true)
#4 /Users/dylan/Sites/vera-c3/vendor/craftcms/cms/src/db/MigrationManager.php(148): craft\db\MigrationManager->migrateUp(Object(dukt\videos\migrations\m190601_092217_tokens))
#5 /Users/dylan/Sites/vera-c3/vendor/craftcms/cms/src/services/Updates.php(227): craft\db\MigrationManager->up()
#6 /Users/dylan/Sites/vera-c3/vendor/craftcms/cms/src/controllers/BaseUpdaterController.php(509): craft\services\Updates->runMigrations(Array)
#7 /Users/dylan/Sites/vera-c3/vendor/craftcms/cms/src/controllers/UpdaterController.php(203): craft\controllers\BaseUpdaterController->runMigrations(Array, 'restore-db')
#8 [internal function]: craft\controllers\UpdaterController->actionMigrate()
#9 /Users/dylan/Sites/vera-c3/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#10 /Users/dylan/Sites/vera-c3/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams(Array)
#11 /Users/dylan/Sites/vera-c3/vendor/craftcms/cms/src/web/Controller.php(181): yii\base\Controller->runAction('migrate', Array)
#12 /Users/dylan/Sites/vera-c3/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('migrate', Array)
#13 /Users/dylan/Sites/vera-c3/vendor/craftcms/cms/src/web/Application.php(294): yii\base\Module->runAction('updater/migrate', Array)
#14 /Users/dylan/Sites/vera-c3/vendor/craftcms/cms/src/web/Application.php(684): craft\web\Application->runAction('updater/migrate')
#15 /Users/dylan/Sites/vera-c3/vendor/craftcms/cms/src/web/Application.php(247): craft\web\Application->_processUpdateLogic(Object(craft\web\Request))
#16 /Users/dylan/Sites/vera-c3/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#17 /Users/dylan/Sites/vera-c3/web/index.php(22): yii\base\Application->run()
#18 {main}

```
### Additional info

- Plugin version: Videos 2.0.10
- Craft version: 3.5.5
- PHP version: 7.2.20
- Database driver & version: MySQL 5.7.26
- Plugins & versions:

**Comment by benjamindavid** [comment]
Shoud be fixed in [2.0.12](https://github.com/dukt/videos/releases/tag/2.0.12).

Thanks for reporting!
