### ISSUE TITLE
Couldn’t load explorer manager.

### ISSUE THREAD

**Issue by svenpeeters** [dukt/videos#8]
```
yii\web\BadRequestHttpException: Request must accept JSON in response in /Users/sven/Projects/@superlab/brusselsphilharmonic.be/vendor/craftcms/cms/src/web/Controller.php:223
Stack trace:
#0 /Users/sven/Projects/@superlab/brusselsphilharmonic.be/vendor/dukt/videos/src/controllers/ExplorerController.php(41): craft\web\Controller->requireAcceptsJson()
#1 [internal function]: dukt\videos\controllers\ExplorerController->actionGetModal()
#2 /Users/sven/Projects/@superlab/brusselsphilharmonic.be/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#3 /Users/sven/Projects/@superlab/brusselsphilharmonic.be/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#4 /Users/sven/Projects/@superlab/brusselsphilharmonic.be/vendor/craftcms/cms/src/web/Controller.php(76): yii\base\Controller->runAction('get-modal', Array)
#5 /Users/sven/Projects/@superlab/brusselsphilharmonic.be/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('get-modal', Array)
#6 /Users/sven/Projects/@superlab/brusselsphilharmonic.be/vendor/craftcms/cms/src/web/Application.php(272): yii\base\Module->runAction('videos/explorer...', Array)
#7 /Users/sven/Projects/@superlab/brusselsphilharmonic.be/vendor/craftcms/cms/src/web/Application.php(520): craft\web\Application->runAction('videos/explorer...', Array)
#8 /Users/sven/Projects/@superlab/brusselsphilharmonic.be/vendor/craftcms/cms/src/web/Application.php(256): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#9 /Users/sven/Projects/@superlab/brusselsphilharmonic.be/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#10 /Users/sven/Projects/@superlab/brusselsphilharmonic.be/web/index.php(21): yii\base\Application->run()
#11 {main}
```

![screen shot 2018-05-02 at 09 06 01](https://user-images.githubusercontent.com/265645/39509876-1021f3ba-4de8-11e8-9a70-2d51af76067e.png)

**Comment by benjamindavid** [comment]
Hey, which video gateway are you trying this with?

**Comment by e-roc** [comment]
I've seen this when not using https, which is required by Google now.

**Comment by benjamindavid** [comment]
Thanks for the feedback @e-roc!

Closing this for now, feel free to reopen if using https doesn't solve the issue.

**Comment by niallthompson** [comment]
I'm having the same issue. Trying to load videos through Youtube gateway.

**Comment by johnwbaxter** [comment]
@benjamindavid  I'm having this issue too. Same as @niallthompson where I'm trying to load YouTube videos.

**Comment by goodmixer** [comment]
@benjamindavid Same issue once I connect Oauth to Google API. Using https.

**Comment by fantasticmachine** [comment]
And same here. Using YouTube with https urls. have set up oAuth.

**Comment by andyharris** [comment]
I'm getting this problem now, seemingly all of a sudden.

**Comment by michalbulla** [comment]
Same issue here, we are using https. Any solutions?

**Comment by a-am** [comment]
We are getting the same issue and we are using HTTPS.  Anyone else have a solution?
