### ISSUE TITLE
Can't uninstall plugin

### ISSUE THREAD

**Issue by alexroper** [dukt/videos#82]
### Description

When I try to uninstall the Videos plugin from the control panel, I get this error:

> Couldn’t uninstall plugin.

In my web.log file, I found this error:

```
2023-06-27 13:49:11 [-][8589][-][error][craft\db\MigrationManager::migrateDown] Failed to revert Install (time: 0.001s). Output:
    > drop index idx_jglbmsklxdrlowaxwbbywzaychurlnyvmvxz on {{%videos_tokens}} ...Exception: SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP INDEX `idx_jglbmsklxdrlowaxwbbywzaychurlnyvmvxz`; check that it exists
The SQL being executed was: DROP INDEX `idx_jglbmsklxdrlowaxwbbywzaychurlnyvmvxz` ON `videos_tokens` (/var/www/html/craft/vendor/yiisoft/yii2/db/Schema.php:676)
#0 /var/www/html/craft/vendor/yiisoft/yii2/db/Command.php(1307): yii\db\Schema->convertException(Object(PDOException), 'DROP INDEX `idx...')
#1 /var/www/html/craft/vendor/yiisoft/yii2/db/Command.php(1102): yii\db\Command->internalExecute('DROP INDEX `idx...')
#2 /var/www/html/craft/vendor/yiisoft/yii2/db/Migration.php(507): yii\db\Command->execute()
#3 /var/www/html/craft/vendor/dukt/videos/src/migrations/Install.php(125): yii\db\Migration->dropIndex('idx_jglbmsklxdr...', '{{%videos_token...')
#4 /var/www/html/craft/vendor/dukt/videos/src/migrations/Install.php(63): dukt\videos\migrations\Install->removeIndexes()
#5 /var/www/html/craft/vendor/craftcms/cms/src/db/Migration.php(90): dukt\videos\migrations\Install->safeDown()
#6 /var/www/html/craft/vendor/craftcms/cms/src/db/MigrationManager.php(293): craft\db\Migration->down(true)
#7 /var/www/html/craft/vendor/craftcms/cms/src/base/Plugin.php(169): craft\db\MigrationManager->migrateDown(Object(dukt\videos\migrations\Install))
#8 /var/www/html/craft/vendor/craftcms/cms/src/services/Plugins.php(628): craft\base\Plugin->uninstall()
#9 /var/www/html/craft/vendor/craftcms/cms/src/controllers/PluginsController.php(88): craft\services\Plugins->uninstallPlugin('videos')
#10 [internal function]: craft\controllers\PluginsController->actionUninstallPlugin()
#11 /var/www/html/craft/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#12 /var/www/html/craft/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#13 /var/www/html/craft/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('uninstall-plugi...', Array)
#14 /var/www/html/craft/vendor/craftcms/cms/src/web/Application.php(295): yii\base\Module->runAction('plugins/uninsta...', Array)
#15 /var/www/html/craft/vendor/craftcms/cms/src/web/Application.php(608): craft\web\Application->runAction('plugins/uninsta...', Array)
#16 /var/www/html/craft/vendor/craftcms/cms/src/web/Application.php(274): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#17 /var/www/html/craft/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#18 /var/www/html/public/index.php(24): yii\base\Application->run()
#19 {main}
```

I believe this has to do with the changes made to Craft 3.6 where index and foreign key names are randomized.

https://craftcms.com/knowledge-base/upgrading-to-craft-3-6#index-and-foreign-key-names

### Possible Solution

I think this file is the culprit: `/vendor/dukt/videos/src/migrations/Install.php`

There is a `removeIndexes()` function on [line 123](https://github.com/dukt/videos/blob/80a339a0a2dd5bf1d0669d8bb0c5dabb54fec93a/src/migrations/Install.php#L123-L126)  that uses `dropIndex`.

```
protected function removeIndexes(): void
{
    $this->dropIndex($this->db->getIndexName(), '{{%videos_tokens}}');
}
```

Updating it to use the [MigrationHelper Class](https://docs.craftcms.com/api/v3/craft-helpers-migrationhelper.html#method-dropindexifexists) worked for me.

```
protected function removeIndexes(): void
{
    MigrationHelper::dropIndexIfExists('{{%videos_tokens}}', 'gateway', false, $this);
}
```

### Possible Workaround

It is possible to uninstall the plugin from the command line using the `--force` flag.

```
$ php craft plugin/uninstall videos --force
```

The error will be logged but the plugin is still uninstalled. The `videos_tokens` table isn't automatically removed from the database so that will need to be deleted manually.

### Steps to reproduce

From the control panel:

1. Go to admin > settings > plugins
2. Click "uninstall" link for Videos

From the command line

1. Run the `craft plugin/uninstall videos` command.

### Additional info

- Plugin version: 2.1.0
- Craft version: Craft Pro 3.8.14
- PHP version: 7.4.33
- Database driver & version: MariaDB 5.5.5
- Plugins & versions:

**Comment by benjamindavid** [comment]
Thanks for the great feedback @alexroper, I'll make sure this is fixed in the next update 👍
